---

- name: install & configure ceilometer juno
  include: juno.yml
  when: (openstack_release == 'juno') and use_ceilometer
  tags: ceilometer

- name: install & configure ceilometer kilo
  include: kilo.yml
  when: (openstack_release == 'kilo') and use_ceilometer
  tags: ceilometer
