---
- name: install ceilometer packages
  yum: pkg={{ item }} state=present
  with_items:
    - openstack-ceilometer-common
    - python-ceilometer
    - python-ceilometerclient
  tags: ceilometer

- name: deploy ceilometer config file for havana or icehouse
  template: src={{ openstack_release }}/ceilometer.conf.j2
            dest=/etc/ceilometer/ceilometer.conf
            mode=0640 owner=root group=ceilometer
  when: openstack_release == 'havana' or openstack_release == 'icehouse'
  tags: ceilometer

- name: Update ceilometer config file for Juno
  command: openstack-config --verbose --set /etc/ceilometer/ceilometer.conf {{ item }}
  with_items:
    - "keystone_authtoken auth_host {{ keystone_admin_vip | default('127.0.0.1') }}"
    - "keystone_authtoken auth_port {{ keystone_auth_port | default(35357) }}"
    - "keystone_authtoken auth_protocol {{ keystone_auth_protocol | default('http') }}"
    - "keystone_authtoken admin_tenant_name services"
    - "keystone_authtoken admin_user ceilometer"
    - "keystone_authtoken admin_password {{ ceilometer_pass }}"
    - "DEFAULT memcached_servers {{ memcached_servers | join(',') }}"
    - "DEFAULT rabbit_hosts {{ rabbit_hosts }}"
    - "DEFAULT rabbit_ha_queues true"
    - "publisher metering_secret {{ ceilometer_metering_secret }}"
    - "service_credentials os_auth_url {{ keystone_auth_protocol | default('http') }}://{{ keystone_private_vip }}:{{ keystone_private_port | default(5000) }}/v2.0"
    - "service_credentials os_username ceilometer"
    - "service_credentials os_tenant_name services"
    - "service_credentials os_password {{ ceilometer_pass }}"
    - "database connection mongodb://{{ controller_node_names | join(',') }}:{{ mongodb_port | default(27017) }}/ceilometer?replicaSet=ceilometer"
    - "database max_retries -1"
    - "database time_to_live {{ ceilometer_time_to_live | default(-1) }}"
    - "api host {{ ceilometer_bind_host }}"
  register: cmd
  changed_when: "'unchanged' not in cmd.stderr"
  when: openstack_release == 'juno'
  tags: ceilometer
