---
neutron_ovs_tenant_network_type: vxlan
neutron_ovs_tunnel_type: vxlan
neutron_ovs_tunnel_id_ranges: 10:10000
neutron_ovs_bridge_mappings: "physnet1:br-ex"
neutron_ovs_integration_bridge: br-int
neutron_ovs_tunnel_bridge: br-tun
use_nova_network: false
use_neutron: true
use_neutron_l3: true
use_neutron_ml2: true
use_neutron_ovs: true
use_neutron_cisco: false
use_nova_nfs_backend: false
use_nova_shared_backend: false
nova_osapi_compute_listen_port: 8774
neutron_auth_strategy: keystone
neutron_enable_security_group: true
neutron_notification_driver: "neutron.openstack.common.notifier.rpc_notifier"
neutron_router_scheduler_driver: "neutron.scheduler.l3_agent_scheduler.ChanceScheduler"
neutron_ovs_firewall_driver: "neutron.agent.linux.iptables_firewall.OVSHybridIptablesFirewallDriver"
neutron_dhcp_agents_per_network: 1
neutron_vxlan_udp_port: 4789
neutron_notify_nova_on_port_status_changes: true
neutron_notify_nova_on_port_data_changes: true
neutron_core_plugin: ml2
use_cinder_nfs_volume_driver: false
