---
-name: use pacemaker to mount the NFS share as service.
  - name: create pacemaker resources for keystone
    pcs_resource: command=create name=glance-fs type=Filesystem clone=yes
    args:
       options:
          device: "{{ wiley-ctlr-1 }}:{{ glance_datadir }}"
          directory: "{{ glance_datadir }}"
          fstype: "nfs"
          options: "v3"
       operations:
        - action: monitor
          options:
            start-delay: 10s
    run_once: true
    when: ansible_distribution_major_version|int == 7
    tags: glance

- name: create pacemaker cloned resources for glance-registry
  pcs_resource: command=create name=glance-registry type=systemd:openstack-glance-registry clone=yes
  args:
    operations:
      - action: monitor
        options:
          start-delay: 10s
  run_once: true
  when: openstack_release == 'juno'
  tags: glance

- name: create pacemaker cloned resources for glance-registry
  pcs_resource: command=create name=glance-registry type=lsb:openstack-glance-registry clone=yes
  args:
    operations:
      - action: monitor
        options:
          start-delay: 10s
  run_once: true
  when: openstack_release == 'juno'
  tags: glance

- name: create pacemaker cloned resources for glance-api
  pcs_resource: command=create name=glance-api type=systemd:openstack-glance-api clone=yes
  args:
    operations:
      - action: monitor
        options:
          start-delay: 10s
  run_once: true
  when: openstack_release == 'juno'
  tags: glance

- name: create pacemaker cloned resources for glance-api
  pcs_resource: command=create name=glance-api type=lsb:openstack-glance-api clone=yes
  args:
    operations:
      - action: monitor
        options:
          start-delay: 10s
  run_once: true
  when: openstack_release == 'juno'
  tags: glance

- name: create pacemaker constraint for glance
  shell: pcs constraint list --full | grep id:order-glance-registry-clone-glance-api-clone-mandatory || pcs constraint order start glance-registry-clone then glance-api-clone
  run_once: true
  tags: glance

