---
- name: create pacemaker resources for glance services
  pcs_resource: command=create name=glance-{{ item }} type=lsb:openstack-glance-{{ item }} clone=yes
  args:
    operations:
      - action: monitor
        options:
          start-delay: 10s
  run_once: true
  with_items:
    - registry
    - api
  tags: ceilometer
