---
# Setting up cinder using nfs until a different driver is supplied
- name: install cinder components
  yum: name={{ item }} state=present
  with_items:
  - openstack-cinder
  - openstack-utils
  - python-memcached
  - python-keystonemiddleware
  - python-openstackclient
  - nfs-utils
  tags: cinder

- name: configure base cinder via openstack-config utility
  command: openstack-config --set --verbose /etc/cinder/cinder.conf {{item}}
  with_items:
    - "DEFAULT verbose true"
    - "DEFAULT debug true"
    - "database connection mysql://cinder:{{ cinder_db_pass }}@{{ lb_db_vip}}/cinder"
    - "database max_retries -1"
    - "DEFAULT auth_strategy keystone"
    - "keystone_authtoken identity_uri {{ keystone_auth_protocol | default('http') }}://{{ keystone_admin_vip }}:{{ keystone_auth_port | default(35357) }}/"
    - "keystone_authtoken auth_uri {{ keystone_public_protocol | default('http') }}://{{ keystone_public_vip }}:{{ keystone_public_port | default(5000) }}/"
    - "keystone_authtoken admin_tenant_name services"
    - "keystone_authtoken admin_user cinder"
    - "keystone_authtoken admin_password {{ cinder_pass }}"
    - "DEFAULT notification_driver messaging"
    - "DEFAULT control_exchange cinder"
    - "DEFAULT glance_host {{ glance_private_vip }}"
    - "DEFAULT memcache_servers {{ memcache_list }}"
    - "DEFAULT rabbit_hosts {{ rabbit_hosts }}"
    - "DEFAULT rabbit_ha_queues true"
    - "DEFAULT host {{ cinder_host }}"
    - "DEFAULT osapi_volume_listen {{ cinder_osapi_volume_listen }}"
    - "DEFAULT osapi_volume_listen_port {{ cinder_osapi_volume_listen_port }}"
  register: cmd
  changed_when: "'unchanged' not in cmd.stderr"
  tags: cinder

- name: configure cinder nfs driver via openstack-config utility
  command: openstack-config --set --verbose /etc/cinder/cinder.conf {{item}}
  with_items:
    - "DEFAULT verbose true"
    - "DEFAULT nfs_shares_config /etc/cinder/nfs_exports"
    - "DEFAULT nfs_sparsed_volumes true"
    - "DEFAULT nfs_mount_options v3"
    - "DEFAULT volume_driver cinder.volume.drivers.nfs.NfsDriver"
  register: cmd
  when: use_cinder_nfs_volume_driver
  changed_when: "'unchanged' not in cmd.stderr"
  tags: cinder

- name: create nfs export directory
  file: state=directory path={{nfs_path}}/cinder owner=root group=cinder mode=0640
  tags: cinder

- name: create cinder nfs export file
  template: src=nfs_exports.j2 dest=/etc/cinder/nfs_exports owner=root group=cinder mode=0640
  when: use_cinder_nfs_volume_driver
  tags: cinder


- name: check for tables
  command: mysql -e "select count(*) from information_schema.tables where table_schema='cinder'" -sN
  run_once: true
  register: mysql_result
  tags: cinder

- name: run dbsync for cinder
  command: runuser cinder -s /bin/sh -c '/usr/bin/cinder-manage db sync'
  when: mysql_result.stdout|int == 0
  run_once: true
  tags: cinder

- name: enable nfs support services
  service: name={{ item }} enabled=yes state=started
  with_items:
    - rpcbind
    - nfslock
  when: use_cinder_nfs_volume_driver
  tags: cinder

- name: disable cinder services
  service: name={{ item }} enabled=no
  with_items:
    - openstack-cinder-api
    - openstack-cinder-scheduler
    - openstack-cinder-volume
  tags: cinder

- name: create pacemaker resources for cinder services
  pcs_resource: command=create name=cinder-{{ item }} type=systemd:openstack-cinder-{{ item }} clone=yes interleave=yes
  args:
    operations:
      - action: monitor
        options:
          start-delay: 10s
  run_once: true
  with_items:
    - api
    - scheduler
  tags: cinder

- name: create pacemaker resource for cinder-volume
  pcs_resource: command=create name=cinder-volume type=systemd:openstack-cinder-volume
  args:
    operations:
      - action: monitor
        options:
          start-delay: 10s
  run_once: true
  tags: cinder

- name: create pacemaker constraints for cinder
  shell: "pcs constraint list --full | grep id:{{ item.id }} || pcs constraint {{ item.cmd }}"
  with_items:
    - { id: order-keystone-clone-cinder-api-clone-mandatory, cmd: "order start keystone-clone then cinder-api-clone" }
    - { id: order-cinder-api-clone-cinder-scheduler-clone-mandatory, cmd: "order start cinder-api-clone then cinder-scheduler-clone" }
    - { id: colocation-cinder-scheduler-clone-cinder-api-clone, cmd: "colocation add cinder-scheduler-clone with cinder-api-clone" }
    - { id: order-cinder-scheduler-clone-cinder-volume-mandatory, cmd: "order start cinder-scheduler-clone then cinder-volume" }
  run_once: true
  register: cmd
  changed_when: "'{{ item.id }}' not in cmd.stdout"
  tags: cinder
