---
- name: create pacemaker resources for cinder services
  pcs_resource: command=create name=cinder-{{ item }} type=systemd:openstack-cinder-{{ item }} clone=yes interleave=yes
  args:
    operations:
      - action: monitor
        options:
          start-delay: 10s
  run_once: true
  with_items:
    - api
    - scheduler
  tags: cinder

- name: create pacemaker resource for cinder-volume
  pcs_resource: command=create name=cinder-volume type=systemd:openstack-cinder-volume
  args:
    operations:
      - action: monitor
        options:
          start-delay: 10s
  tags: cinder
