- name: install mongodb packages
  yum: pkg={{ item }} state=present
  with_items:
    - mongodb-2.6.5-2.el7ost.x86_64
    - mongodb-server-2.6.5-2.el7ost.x86_64
  tags: mongodb

- name: start mongodb
  service: name=mongod state=started
  tags: mongodb

- name: stop mongodb
  service: name=mongod state=stopped
  tags: mongodb

- name: update mongod.conf for small files/bindip/and replset
  template: src=mongodb.conf.j2 dest=/etc/mongodb.conf owner=mongodb group=mongodb mode=644
  tags: mongodb

- name: create data directory for mongodb
  file: path=/var/lib/mongodb state=directory owner=mongodb group=mongodb mode=0750
  tags: mongodb

- name: create pid directory for mongodb
  file: path=/var/run/mongodb/ state=directory owner=mongodb group=mongodb mode=0774

- name: start mongodb
  service: name=mongod state=started
  tags: mongodb


#- name: update mongod.conf for small files/bindip/and replset
#  template: src=mongodb.conf.j2 dest=/etc/mongodb.conf owner=mongodb group=mongodb mode=644
#  tags: mongodb

#- name: restart mongodb
#  service: name=mongod state=started
#  tags: mongodb


- name: load replica set config
  template: src=repset_init.j2 dest=/tmp/repset_init.js
  tags: mongodb

#- name: pause for a while
#  wait_for: timeout=20
#  tags: mongodb

- name: initialize the replication set
  command: /usr/bin/mongo --host "{{ mongodb_bind_host }}" --port "{{ mongodb_port | default(27017) }}" /tmp/repset_init.js
  #command: /usr/bin/mongo /tmp/repset_init.js
  run_once: true
  tags: mongodb

- include: rhel7-juno-cluster-resources.yml
  when: openstack_release == 'juno' and ansible_distribution_major_version|int == 7
  tags: mongodb

#- name: add mongo to pcs
#  command: pcs resource create mongodb systemd:mongod op start timeout=300s --clone
#  tags: mongodb

- name: pause to allow primary election and sync of replica set
  wait_for: timeout=60
  tags: mongodb

- name: cleanup pcs resouce
  command: pcs resource cleanup mongodb
  tags: mongodb

