---
- name: Controller Interface Configuration
  hosts: controller
  max_fail_percentage: 0
  roles:
    - role: iface
      device: p3p1
      params:
        type: Ethernet
        bootproto: none
        onboot: '"yes"'
        peerdns: '"no"'
        master: bond0
        slave: '"yes"'

    - role: iface
      device: p3p2
      params:
        type: Ethernet
        bootproto: none
        onboot: '"yes"'
        peerdns: '"no"'
        master: bond0
        slave: '"yes"'

    - role: iface
      device: bond0
      params:
        nozeroconf: '"yes"'
        bootproto: none
        bonding_opts: '"miimon=100 mode=802.3ad"'
        onboot: '"yes"'
        peerdns: '"no"'

    - role: iface
      device: "bond0.{{ int_if.vlan }}"
      params:
        type: Ethernet
        vlan: '"yes"'
        nozeroconf: '"yes"'
        bootproto: static
        ipaddr: "{{ int_if.ipaddr }}"
        netmask: "{{ int_if.netmask }}"
        gateway: "{{ int_if.gateway }}"
        defroute: '"yes"'
        onboot: '"yes"'
        peerdns: '"no"'

    - role: iface
      device: "bond0.{{ storage_if.vlan }}"
      params:
        type: Ethernet
        vlan: '"yes"'
        nozeroconf: '"yes"'
        bootproto: static
        ipaddr: "{{ storage_if.ipaddr }}"
        netmask: "{{ storage_if.netmask }}"
        onboot: '"yes"'
        peerdns: '"no"'

    - role: iface
      device: "bond0.{{ ext_if.vlan }}"
      params:
        devicetype: ovs
        type: OVSPort
        vlan: '"yes"'
        nm_controlled: '"no"'
        nozeroconf: '"yes"'
        ovs_bridge: br-ex
        onboot: '"yes"'
        peerdns: '"no"'

    - role: iface
      device: "bond0.{{ tun_if.vlan }}"
      params:
        type: Ethernet
        vlan: '"yes"'
        nozeroconf: '"yes"'
        bootproto: static
        ipaddr: "{{ tun_if.ipaddr }}"
        netmask: "{{ tun_if.netmask }}"
        onboot: '"yes"'
        peerdns: '"no"'

    - role: iface
      device: br-ex
      params:
        devicetype: ovs
        type: OVSBridge
        onboot: '"yes"'
        ovsbootproto: static
        nozeroconf: '"yes"'
        ipaddr: "{{ ext_if.ipaddr }}"
        netmask: "{{ ext_if.netmask }}"
        peerdns: '"no"'

- name: Controller OpenStack Installation
  hosts: controller
  max_fail_percentage: 0
  roles:
    - pacemaker
    - haproxy
    - memcached
    - rabbitmq
    - galera
    - mongodb
    - keystone
    - glance
    - cinder
    - neutron
    - nova-common
    - nova-control
    - heat
    - ceilometer-common
    - ceilometer-control
    - horizon
