---

- hosts:
    - openstack
    - scaleio
  roles:
    - subscription-manager
    - common

- hosts: openstack
  roles:
    - openstack-common

- include: controllers.yml
- include: swift.yml
- include: compute-nodes.yml
- include: scaleio-nodes.yml
