---

- hosts:
    - openstack
    - scaleio
  max_fail_percentage: 0
  roles:
    - subscription-manager
    - common

- hosts: openstack
  max_fail_percentage: 0
  roles:
    - openstack-common

- include: controllers.yml
- include: swift.yml
- include: compute-nodes.yml
- include: scaleio-nodes.yml
- include: demo.yml
