- hosts: swift
  roles:
    - role: iface
      device: p3p1
      params:
        type: Ethernet
        bootproto: none
        onboot: '"yes"'
        peerdns: '"no"'
        master: bond0
        slave: '"yes"'
        mtu: 9000

    - role: iface
      device: p3p2
      params:
        type: Ethernet
        bootproto: none
        onboot: '"yes"'
        peerdns: '"no"'
        master: bond0
        slave: '"yes"'
        mtu: 9000

    - role: iface
      device: bond0
      params:
        nozeroconf: '"yes"'
        bootproto: none
        bonding_opts: '"miimon=100 mode=802.3ad"'
        onboot: '"yes"'
        mtu: 9000
        peerdns: '"no"'

    - role: iface
      device: "bond0.{{ int_if.vlan }}"
      params:
        mtu: 9000
        type: Ethernet
        vlan: '"yes"'
        nozeroconf: '"yes"'
        bootproto: static
        ipaddr: "{{ int_if.ipaddr }}"
        netmask: "{{ int_if.netmask }}"
        gateway: "{{ int_if.gateway }}"
        defroute: "yes"
        onboot: '"yes"'
        peerdns: '"no"'

    - role: iface
      device: "bond0.{{ storage_if.vlan }}"
      params:
        type: Ethernet
        mtu: 9000
        vlan: '"yes"'
        nozeroconf: '"yes"'
        bootproto: static
        ipaddr: "{{ storage_if.ipaddr }}"
        netmask: "{{ storage_if.netmask }}"
        onboot: '"yes"'
        peerdns: '"no"'

   # - role: iface
   #   device: "bond0.{{ swift_if.vlan }}"
   #   params:
   #     mtu: 9000
   #     type: ethernet
   #     vlan: '"yes"'
   #     nm_controlled: '"no"'
   #     nozeroconf: '"yes"'
   #     onboot: '"yes"'
   #     ipaddr: "{{ swift_if.ipaddr}}"
   #     netmask: "{{ swift_if.ipaddr}}"

- hosts: controller
  roles:
    - swift-proxy-1

- hosts: swift
  roles:
    - swift-storage-1

- hosts: controller
  roles:
    - swift-proxy-2

- hosts: swift
  roles:
    - swift-storage-2

- hosts: controller
  roles:
    - swift-glance
