---
- include: "RedHat-rpms.yml"
  when: ansible_os_family == "RedHat"
  tags: openstack-common

- name: disable NetworkManager
  service: name=NetworkManager enabled=no state=stopped
  tags: openstack-common
