---
- name: install rpms useful for OpenStack operations and troubleshooting
  yum: name={{ item }} state=present
  with_items:
    - nfs-utils
    - iscsi-initiator-utils
    - bridge-utils
    - net-tools
    - traceroute
    - tcpdump
    - sos
