---
- name: iptable rules for nova-controller
  iptables:
    port: "{{ item.port }}"
    protocol: "{{ item.protocol}}"
    comment: "{{item.comment}}"
  with_items:
    - { port: 6080, protocol: tcp, comment: "novncproxy" }
    - { port: 8774, protocol: tcp, comment: "nova api"}
    - { port: 8775, protocol: tcp, comment: "nova api"}
    - { port: 8773, protocol: tcp, comment: "nova api"}
  tags:
    - iptables
    - nova

- name: install nova packages
  yum: pkg={{ item }} state=present
  with_items:
    - openstack-nova-console
    - openstack-nova-novncproxy
    - openstack-utils
    - openstack-nova-api
    - openstack-nova-conductor
    - openstack-nova-scheduler
    - python-cinderclient
    - python-memcached
  tags: nova

- name: Update nova.conf file
  command: openstack-config --verbose --set /etc/nova/nova.conf {{ item }}
  with_items:
    - "DEFAULT verbose true"
    - "DEFAULT vncserver_proxyclient_address {{ internal_ipaddr }}"
    - "DEFAULT vncserver_listen {{ internal_ipaddr }}"
    - "DEFAULT novncproxy_host {{ internal_ipaddr }}"
    - "DEFAULT novncproxy_base_url http://{{ nova_public_vip }}:6080/vnc_auto.html"
    - "DEFAULT novncproxy_host {{ internal_ipaddr}}"
    - "database connection mysql://nova:{{ nova_db_pass }}@{{ lb_db_vip }}/nova"
    - "database max_retries -1"
    - "DEFAULT auth_strategy keystone"
    - "DEFAULT memcache_servers {{ memcached_servers }}"
    - "DEFAULT rabbit_hosts {{ rabbit_hosts }}"
    - "DEFAULT rabbit_ha_queues true"
    - "DEFAULT osapi_compute_listen {{ internal_ipaddr }}"
    - "DEFAULT metadata_host {{ nova_private_vip }}"
    - "DEFAULT metadata_listen {{ internal_ipaddr }}"
    - "DEFAULT metadata_listen_port {{ nova_metadata_port }}"
    - "neutron service_metadata_proxy True"
    - "neutron metadata_proxy_shared_secret {{ neutron_metadata_proxy_shared_secret }}"
    - "DEFAULT glance_host {{ glance_private_vip }}"
    - "DEFAULT glance_port {{ glance_port | default(9292) }}"
    - "DEFAULT network_api_class nova.network.neutronv2.api.API"
    - "DEFAULT neutron_url http://{{ neutron_private_vip | default('127.0.0.1') }}:{{ neutron_port | default(9696) }}/"
    - "DEFAULT neutron_admin_tenant_name services"
    - "DEFAULT neutron_admin_username neutron"
    - "DEFAULT neutron_admin_password {{ neutron_pass }}"
    - "DEFAULT neutron_admin_auth_url http://{{ keystone_private_vip | default('127.0.0.1') }}:{{ keystone_private_port | default(5000) }}/v2.0"
    - "DEFAULT ovs_bridge br-int"
    - "DEFAULT auth_strategy keystone"
    - "DEFAULT firewall_driver nova.virt.firewall.NoopFirewallDriver"
    - "DEFAULT libvirt_vif_driver nova.virt.libvirt.vif.LibvirtGenericVIFDriver"
    - "DEFAULT security_group_api {{ nova_security_group_api }}"
    - "conductor use_local false"
    - "DEFAULT scheduler_host_subset_size 30"
    - "DEFAULT notification_topics notifications"
    - "DEFAULT notification_driver ceilometer.compute.nova_notifier"
    - "DEFUALT notification_driver nova.openstack.common.notifier.rpc_notifier"
    - "DEFAULT rpc_backend nova.openstack.common.rpc.impl_kombu"
  register: cmd
  changed_when: "'unchanged' not in cmd.stderr"
  tags: nova

- name: add novnc vip /etc/hosts with all nodes
  tags: nova
  lineinfile: dest=/etc/hosts  line="{{ nova_vip }} {{inventory_hostname}}" state=present

- name: check for tables
  command: mysql -e "select count(*) from information_schema.tables where table_schema='nova'" -sN
  run_once: true
  register: mysql_result
  tags: nova

- name: run dbsync for nova
  shell: runuser nova -s /bin/sh -c '/usr/bin/nova-manage db sync'
  when: mysql_result.stdout|int == 0
  run_once: true
  tags: nova

- name: disable nova services
  service: name={{ item }} enabled=no
  with_items:
    - openstack-nova-consoleauth
    - openstack-nova-novncproxy
    - openstack-nova-api
    - openstack-nova-scheduler
    - openstack-nova-conductor
  tags: nova

- name: create pacemaker resources for nova control services
  pcs_resource: command=create name=nova-{{ item }} type=systemd:openstack-nova-{{ item }} clone=yes
  args:
    operations:
      - action: monitor
        options:
          start-delay: 10s
  run_once: true
  with_items:
    - novncproxy
    - api
    - scheduler
    - conductor
  tags: nova

- name: create pacemaker resources for nova consoleauth
  pcs_resource: command=create name=nova-consoleauth type=systemd:openstack-nova-consoleauth
  args:
    operations:
      - action: monitor
        options:
          start-delay: 10s
  run_once: true

- name: create pacemaker constraints for nova-control
  shell: "pcs constraint list --full | grep id:{{ item.id }} || pcs constraint {{ item.cmd }}"
  with_items:
    - { id: order-nova-api-clone-nova-novncproxy-clone-mandatory, cmd: "order start nova-api-clone then nova-novncproxy-clone" }
    - { id: colocation-nova-api-clone-nova-novncproxy-clone, cmd: "colocation add nova-api-clone with nova-novncproxy-clone" }
    - { id: order-nova-api-clone-nova-scheduler-clone-mandatory, cmd: "order start nova-api-clone then nova-scheduler-clone" }
    - { id: colocation-nova-scheduler-clone-nova-api-clone, cmd: "colocation add nova-scheduler-clone with nova-api-clone" }
    - { id: order-nova-scheduler-clone-nova-conductor-clone-mandatory, cmd: "order start nova-scheduler-clone then nova-conductor-clone" }
    - { id: colocation-nova-conductor-clone-nova-scheduler-clone, cmd: "colocation add nova-conductor-clone with nova-scheduler-clone" }
  run_once: true
  register: cmd
  changed_when: "'{{ item.id }}' not in cmd.stdout"
  tags: nova
