---
- name: install nova packages
  yum: pkg={{ item }} state=present
  with_items:
    - openstack-nova-console
    - openstack-nova-novncproxy
    - openstack-utils
    - openstack-nova-api
    - openstack-nova-conductor
    - openstack-nova-scheduler
    - python-cinderclient
    - python-memcached
  tags: nova

- name: Update nova.conf file for Juno
  command: openstack-config --verbose --set /etc/nova/nova.conf {{ item }}
  with_items:
    - "DEFAULT verbose true"
    - "DEFAULT vncserver_proxyclient_address {{ internal_ipaddr }}"
    - "DEFAULT vncserver_listen {{ internal_ipaddr }}"
    - "DEFAULT novncproxy_host {{ internal_ipaddr }}"
    - "DEFAULT novncproxy_base_url http://{{ nova_public_vip }}:6080/vnc_auto.html"
    - "DEFAULT novncproxy_host {{ internal_ipaddr}}"
    - "database connection mysql://nova:{{ nova_db_pass }}@{{ lb_db_vip }}/nova"
    - "database max_retries -1"
    - "DEFAULT auth_strategy keystone"
    - "DEFAULT memcache_servers {{ memcached_servers|join(',') }}"
    - "DEFAULT rabbit_hosts {{ rabbit_hosts }}"
    - "DEFAULT rabbit_ha_queues true"
    - "DEFAULT osapi_compute_listen {{ internal_ipaddr }}"
    - "DEFAULT metadata_host {{ nova_private_vip }}"
    - "DEFAULT metadata_listen {{ internal_ipaddr }}"
    - "DEFAULT metadata_listen_port {{ nova_metadata_port }}"
    - "neutron service_neutron_metadata_proxy True"
    - "neutron neutron_metadata_proxy_shared_secret {{ neutron_metadata_proxy_shared_secret }}"
    - "DEFAULT glance_host {{ glance_private_vip }}"
    - "DEFAULT glance_port {{ glance_port | default(9292) }}"
    - "DEFAULT network_api_class nova.network.neutronv2.api.API"
    - "DEFAULT neutron_url http://{{ neutron_private_vip | default('127.0.0.1') }}:{{ neutron_port | default(9696) }}/"
    - "DEFAULT neutron_admin_tenant_name services"
    - "DEFAULT neutron_admin_username neutron"
    - "DEFAULT neutron_admin_password {{ neutron_pass }}"
    - "DEFAULT neutron_admin_auth_url http://{{ keystone_private_vip | default('127.0.0.1') }}:{{ keystone_private_port | default(5000) }}/v2.0"
    - "DEFAULT ovs_bridge br-int"
    - "DEFAULT auth_strategy keystone"
    - "DEFAULT firewall_driver nova.virt.firewall.NoopFirewallDriver"
    - "DEFAULT libvirt_vif_driver nova.virt.libvirt.vif.LibvirtGenericVIFDriver"
    - "DEFAULT security_group_api {{ nova_security_group_api }}"
    - "conductor use_local false"
    - "DEFAULT scheduler_host_subset_size 30"
    - "DEFAULT notification_topics notifications"
    - "DEFAULT notification_driver ceilometer.compute.nova_notifier"
    - "DEFUALT notification_driver nova.openstack.common.notifier.rpc_notifier"
    - "DEFAULT rpc_backend nova.openstack.common.rpc.impl_kombu"
  register: cmd
  when: openstack_release == 'juno'
  changed_when: "'unchanged' not in cmd.stderr"
  tags: nova


- name: check for tables
  command: mysql -e "select count(*) from information_schema.tables where table_schema='nova'" -sN
  run_once: true
  register: mysql_result
  tags: nova

- name: run dbsync for nova
  shell: runuser nova -s /bin/sh -c '/usr/bin/nova-manage db sync'
  when: mysql_result.stdout|int == 0
  run_once: true
  tags: nova

- name: disable nova services
  service: name={{ item }} enabled=no
  with_items:
    - openstack-nova-consoleauth
    - openstack-nova-novncproxy
    - openstack-nova-api
    - openstack-nova-scheduler
    - openstack-nova-conductor
  tags: nova

- include: rhel7-icehouse-cluster-resources.yml
  when: openstack_release == 'icehouse' and ansible_distribution_major_version|int == 7
  tags: nova

- include: rhel6-icehouse-cluster-resources.yml
  when: openstack_release == 'icehouse' and ansible_distribution_major_version|int == 6
  tags: nova

- include: rhel6-havana-cluster-resources.yml
  when: openstack_release == 'havana' and ansible_distribution_major_version|int == 6
  tags: nova

- include: juno-cluster-resources.yml
  when: openstack_release == 'juno'
  tags: nova

- include: cluster-constraints.yml
  tags: nova
