#Slimer Variables
mtu: 8964
# subscription manager vars:
rhn_pass: 'rhn-password'
rhn_user: 'rhn-user-name'
pool: 'Red Hat Enterprise Linux OpenStack Platform Developer Supported Business Partner NFR'

### OpenStack control plane configuration
admin_tenant: admin
admin_user: admin
openstack_release: juno
use_swift: true
use_ceph: false
use_stonith: false
keystone_auth_port: 35357
keystone_auth_protocol: http
keystone_adminurl: "{{ keystone_auth_protocol }}://{{ keystone_vip }}:{{ keystone_auth_port }}/v2.0"

#offline var, if true then installation will use an local repo for rpms
offline: true

search_domain: ".lordbusiness"
nameservers:
 - 192.168.70.3

### Network interface assignment
# any deviations for individual hosts should be specified in the host_vars or inventory files
primary_if: bond0.1805
private_if: bond0.1801
tunnel_if: bond0.1802

### NTP servers
ntp:
  - 0.rhel.pool.ntp.org
  - 1.rhel.pool.ntp.org
  - 2.rhel.pool.ntp.org

neutron_ovs_bridges:
  - bridge: br-ex
    port: bond0.1805

default_store: swift
temporary_dir: /var/lib/ansible
credentials_dir: /var/lib/ansible
pcs_cluster_name: automation_cluster
pcs_cluster_pass: "{{ lookup('password', credentials_dir + '/credentials/pcs_cluster_pass chars=ascii_letters,digits') }}"
rabbit_hosts: "{% for node in groups['controller'] %}{{ hostvars[node]['ansible_'+private_if]['ipv4']['address'] }}:5672{% if not loop.last %},{% endif %}{% endfor %}"
memcache_servers: "{% for node in groups['controller'] %}{{ hostvars[node]['ansible_'+private_if]['ipv4']['address'] }}:11211{% if not loop.last %},{% endif %}{% endfor %}"

#database user passwords
clustercheck_db_pass: "{{ lookup('password', credentials_dir + '/credentials/clustercheck_db_pass chars=ascii_letters,digits') }}"
db_root_password: "{{ lookup('password', credentials_dir + '/credentials/db_root_password chars=ascii_letters,digits') }}"
keystone_db_pass: "{{ lookup('password', credentials_dir + '/credentials/keystone_db_pass chars=ascii_letters,digits') }}"
glance_db_pass: "{{ lookup('password', credentials_dir + '/credentials/glance_db_pass chars=ascii_letters,digits') }}"
cinder_db_pass: "{{ lookup('password', credentials_dir + '/credentials/cinder_db_pass chars=ascii_letters,digits') }}"
nova_db_pass: "{{ lookup('password', credentials_dir + '/credentials/nova_db_pass chars=ascii_letters,digits') }}"
neutron_db_pass: "{{ lookup('password', credentials_dir + '/credentials/neutron_db_pass chars=ascii_letters,digits') }}"
heat_db_pass: "{{ lookup('password', credentials_dir + '/credentials/heat_db_pass chars=ascii_letters,digits') }}"
swift_db_pass: "{{ lookup('password', credentials_dir + '/credentials/swift_db_pass chars=ascii_letters,digits') }}"

#openstack service user passwords
admin_pass: "{{ lookup('password', credentials_dir + '/credentials/admin_pass chars=ascii_letters,digits') }}"
glance_pass: "{{ lookup('password', credentials_dir + '/credentials/glance_pass chars=ascii_letters,digits') }}"
cinder_pass: "{{ lookup('password', credentials_dir + '/credentials/cinder_pass chars=ascii_letters,digits') }}"
swift_pass: "{{ lookup('password', credentials_dir + '/credentials/swift_pass chars=ascii_letters,digits') }}"
neutron_pass: "{{ lookup('password', credentials_dir + '/credentials/neutron_pass chars=ascii_letters,digits') }}"
nova_pass: "{{ lookup('password', credentials_dir + '/credentials/nova_pass chars=ascii_letters,digits') }}"
heat_pass: "{{ lookup('password', credentials_dir + '/credentials/heat_pass chars=ascii_letters,digits') }}"
ceilometer_pass: "{{ lookup('password', credentials_dir + '/credentials/ceilometer_pass chars=ascii_letters,digits') }}"
keystone_admin_token: "{{ lookup('password', credentials_dir + '/credentials/keystone_admin_token chars=hexdigits') }}"
swift_pathprefix: "{{ lookup('password', credentials_dir + '/credentials/swift_prefix chars=ascii_letters,digits') }}"
swift_pathsuffix: "{{ lookup('password', credentials_dir + '/credentials/swift_suffix chars=ascii_letters,digits') }}"
demo_pass: "{{ lookup('password', credentials_dir + '/credentials/admin_pass chars=ascii_letters,digits') }}"
neutron_metadata_proxy_shared_secret: "{{ lookup('password', credentials_dir + '/credentials/neutron_metadata_proxy_shared_secret chars=hexdigits') }}"

#Internal VIPs
rabbit_vip: 172.17.17.100
lb_db_vip: 172.17.17.101
keystone_vip: 172.17.17.103
glance_vip: 172.17.17.104
cinder_vip: 172.17.17.105
nova_vip: 172.17.17.106
neutron_vip: 172.17.17.107
horizon_vip: 172.17.17.108
heat_vip: 172.17.17.109
ceilometer_vip: 172.17.17.110
swift_vip: 172.17.17.111
scaleio_vip: 172.17.17.112
#vip_swift_pub: 172.17.17.113
vip_keystone_pub: 172.17.17.114
vip_glance_pub: 172.17.17.115
vip_cinder_pub: 172.17.17.116
vip_nova_pub: 172.17.17.117
vip_neutron_pub: 172.17.17.118
vip_horizon_pub: 172.17.17.119
vip_heat_pub: 172.17.17.120
vip_ceilometer_pub: 172.17.17.121

### Horizon
#horizon_internal_servername: vip-horizon-int.business
#horizon_public_servername: vip-horizon-pub.business
horizon_internal_servername: 172.17.17.108
horizon_public_servername: 172.17.17.119

# Toggle whether or not the demo role should be run
run_demo: true
