---
# If pcs has galera listed and is master. do not run include
- name: check for galera-master in pcs
  shell: pcs status | grep galera -a1 | tail -n1
  register: pcs_result
  run_once: yes
  tags: mysql

- name: start galera deploy
  include: galera.yml
  when: '"Masters" not in pcs_result.stdout'
  tags: mysql
