---
public_ipaddr: "{{ hostvars[inventory_hostname][ 'ansible_' + primary_if ].ipv4.address }}"
internal_ipaddr: "{{ hostvars[inventory_hostname][ 'ansible_' + private_if ].ipv4.address }}"
ceilometer_bind_host: "{{ internal_ipaddr }}"
memcached_servers: "{% for node in groups['controller'] %}{{ hostvars[node][ 'ansible_' + primary_if ].ipv4.address  }}:11211{% if not loop.last %},{% endif %}{% endfor %}"
rabbit_hosts: "{% for node in groups['controller'] %}{{ hostvars[node][ 'ansible_' + primary_if ].ipv4.address  }}:5672{% if not loop.last %},{% endif %}{% endfor %}"
