---
- name: install heat packages
  yum: pkg={{ item }} state=present
  with_items:
    - openstack-heat-common
    - openstack-heat-api
    - openstack-heat-api-cfn
    - openstack-heat-api-cloudwatch
    - openstack-heat-engine
    - python-heatclient
    - python-glanceclient
    - openstack-utils
    - openstack-selinux
  tags: heat

- name: Update heat config file
  command: openstack-config --verbose --set /etc/heat/heat.conf {{ item }}
  with_items:
    - "DEFAULT verbose true"
    - "database connection mysql://heat:{{ heat_db_pass }}@{{ lb_db_vip }}/heat"
    - "database max_retries -1"
    - "keystone_authtoken admin_tenant_name services"
    - "keystone_authtoken admin_user heat"
    - "keystone_authtoken admin_password {{ heat_pass }}"
    - "keystone_authtoken auth_host {{ keystone_admin_vip | default('127.0.0.1') }}"
    - "keystone_authtoken auth_port {{ keystone_auth_port | default(35357) }}"
    - "keystone_authtoken auth_protocol {{ keystone_auth_protocol | default('http') }}"
    - "keystone_authtoken auth_uri {{ keystone_auth_protocol | default('http') }}://{{ keystone_admin_vip }}:{{ keystone_auth_port | default(35357) }}/v2.0"
    - "DEFAULT memcached_servers {{ memcached_servers | join(',') }}"
    - "DEFAULT rabbit_hosts {{ rabbit_hosts }}"
    - "DEFAULT rabbit_ha_queues true"
    - "heat_api bind_host {{ heat_bind_host }}"
    - "heat_api_cfn bind_host {{ heat_bind_host }}"
    - "heat_api_cloudwatch bind_host {{ heat_bind_host }}"
    - "DEFAULT heat_metadata_server_url {{ heat_metadata_server_url }}"
    - "DEFAULT heat_waitcondition_server_url {{ heat_waitcondition_server_url }}"
    - "DEFAULT heat_watch_server_url {{ heat_watch_server_url }}"
    - "DEFAULT rpc_backend heat.openstack.common.rpc.impl_kombu"
    - "DEFAULT notification_driver heat.openstack.common.notifier.rpc_notifier"
  register: cmd
  changed_when: "'unchanged' not in cmd.stderr"
  tags: heat

- name: check for tables
  command: mysql -e "select count(*) from information_schema.tables where table_schema='heat'" -sN
  run_once: true
  register: mysql_result
  tags: heat

- name: run dbsync for heat
  shell: su -s /bin/sh -c '/usr/bin/heat-manage db_sync' heat
  when: mysql_result.stdout|int == 0
  run_once: true
  tags: heat

- name: restart and disable heat
  service: name={{ item }} state=restarted enabled=no
  with_items:
    - openstack-heat-api
    - openstack-heat-api-cfn
    - openstack-heat-api-cloudwatch
    - openstack-heat-engine
  tags: heat

- name: create pacemaker resources for heat
  pcs_resource: command=create name={{ item }} type=systemd:openstack-{{ item }} clone=yes
  args:
    operations:
      - action: monitor
        options:
          start-delay: 10s
  run_once: true
  with_items:
    - heat-api
    - heat-api-cfn
    - heat-api-cloudwatch
  tags: heat

- name: create pacemaker resource for heat-engine
  pcs_resource: command=create name=heat-engine type=systemd:openstack-heat-engine
  args:
    operations:
      - action: monitor
        options:
          start-delay: 10s
  run_once: true
  tags: heat

- name: create pacemaker constraints for heat
  shell: "pcs constraint list --full | grep id:{{ item.id }} || pcs constraint {{ item.cmd }}"
  with_items:
    - { id: order-heat-api-clone-heat-api-cfn-clone-mandatory, cmd: "order start heat-api-clone then heat-api-cfn-clone" }
    - { id: colocation-heat-api-clone-heat-api-cfn-clone, cmd: "colocation add heat-api-cfn-clone with heat-api-clone" }
    - { id: order-heat-api-cfn-clone-heat-api-cloudwatch-clone-mandatory, cmd: "order start heat-api-cfn-clone then heat-api-cloudwatch-clone" }
    - { id: colocation-heat-api-cloudwatch-clone-heat-api-cfn-clone, cmd: "colocation add heat-api-cloudwatch-clone with heat-api-cfn-clone" }
    - { id: order-heat-api-cloudwatch-clone-heat-engine-mandatory, cmd: "order start heat-api-cloudwatch-clone then heat-engine" }
    - { id: colocation-heat-engine-heat-api-cloudwatch-clone, cmd: "colocation add heat-engine with heat-api-cloudwatch-clone" }
  run_once: true
  register: cmd
  changed_when: "'{{ item.id }}' not in cmd.stdout"
  tags: heat
