---
- name: install & configure heat juno
  include: juno.yml
  when: (openstack_release == 'juno') and use_heat
  tags: heat

- name: install & configure heat kilo
  include: kilo.yml
  when: (openstack_release == 'kilo') and use_heat
  tags: heat
