---
- name: create pacemaker resources for neutron-server
  pcs_resource: command=create name=neutron-server type=systemd:neutron-server clone=yes interleave=yes
  args:
    operations:
      - action: monitor
        options:
          start-delay: 10s
  run_once: true
  tags: neutron

- name: neutron-scale TEMP
  command: pcs resource create neutron-scale ocf:neutron:NeutronScale --clone globally-unique=true clone-max=3 interleave=true
  run_once: true
  ignore_errors: true
  tags: neutron

#- name: create pacemaker resource for neutron-scale
#  pcs_resource: command=create name=neutron-scale type=ocf:neutron:NeutronScale clone=yes interleave=yes
#  args:
#    operations:
#      - action: monitor
#        options:
#          start-delay: 10s
#    options:
#      globally-unique: true
#      clone-max: 3
#  run_once: true
#  tags: neutron

- name: create pacemaker resource for neutron agents
  pcs_resource: command=create name={{ item.name }} type={{ item.type }} clone=yes interleave=yes
  args:
    operations:
      - action: monitor
        options:
          start-delay: 10s
  run_once: true
  with_items:
    - { name: 'neutron-ovs-cleanup', type: 'ocf:neutron:OVSCleanup' }
    - { name: 'neutron-netns-cleanup', type: 'ocf:neutron:NetnsCleanup' }
    - { name: 'neutron-openvswitch-agent', type: 'systemd:neutron-openvswitch-agent' }
    - { name: 'neutron-dhcp-agent', type: 'systemd:neutron-dhcp-agent' }
    - { name: 'neutron-l3-agent', type: 'systemd:neutron-l3-agent' }
    - { name: 'neutron-metadata-agent', type: 'systemd:neutron-metadata-agent' }
  tags: neutron
