---
- name: install neutron packages
  yum: pkg={{ item }} state=present
  with_items:
    - openstack-neutron
    - openstack-utils
    - openstack-selinux
    - openvswitch
    - openstack-neutron-ml2
  when: use_neutron
  tags: neutron

- name: start openvswitch
  service: name=openvswitch enabled=yes state=started
  when: use_neutron
  tags: neutron

- name: get tenant services uuid
  shell: source /root/keystonerc_admin; keystone tenant-get services | awk '/id/ { print $4 }'
  register: tenant_services_uuid
  when: use_neutron
  tags: neutron

- name: openstack-command set bind_host
  command: openstack-config --verbose --set /etc/neutron/neutron.conf DEFAULT bind_host {{ neutron_bind_host }}
  register: cmd
  changed_when: "'changed' in cmd.stderr"

- name: openstack-command set auth_strategy
  command: openstack-config --verbose --set /etc/neutron/neutron.conf DEFAULT auth_strategy {{ neutron_auth_strategy }}
  register: cmd
  changed_when: "'changed' in cmd.stderr"

- name: openstack-command set admin_tenant_name
  command: openstack-config --verbose --set /etc/neutron/neutron.conf keystone_authtoken admin_tenant_name services
  register: cmd
  changed_when: "'changed' in cmd.stderr"

- name: openstack-command set admin_user
  command: openstack-config --verbose --set /etc/neutron/neutron.conf keystone_authtoken admin_user neutron
  register: cmd
  changed_when: "'changed' in cmd.stderr"

- name: openstack-command set admin_password
  command: openstack-config --verbose --set /etc/neutron/neutron.conf keystone_authtoken admin_password {{ neutron_pass }}
  register: cmd
  changed_when: "'changed' in cmd.stderr"

- name: openstack-command set auth_uri
  command: openstack-config --verbose --set /etc/neutron/neutron.conf keystone_authtoken auth_uri {{ keystone_auth_protocol | default('http') }}://{{ keystone_admin_vip }}:{{ keystone_auth_port | default(35357) }}/v2.0
  register: cmd
  changed_when: "'changed' in cmd.stderr"

- name: openstack-command set identity_uri
  command: openstack-config --verbose --set /etc/neutron/neutron.conf keystone_authtoken identity_uri  {{ keystone_auth_protocol | default('http') }}://{{ keystone_admin_vip }}:{{ default(5000) }}
  register: cmd
  changed_when: "'changed' in cmd.stderr"

- name: openstack-command set connection
  command: openstack-config --verbose --set /etc/neutron/neutron.conf database connection mysql://neutron:{{ neutron_db_pass }}@{{ lb_db_vip }}/neutron
  register: cmd
  changed_when: "'changed' in cmd.stderr"

- name: openstack-command set max_retries
  command: openstack-config --verbose --set /etc/neutron/neutron.conf database max_retries -1
  register: cmd
  changed_when: "'changed' in cmd.stderr"

- name: openstack-command set rabbit_hosts
  command: openstack-config --verbose --set /etc/neutron/neutron.conf oslo_messaging_rabbit rabbit_hosts {{ rabbit_host }}
  register: cmd
  changed_when: "'changed' in cmd.stderr"

- name: openstack-command set rabbit_ha_queues
  command: openstack-config --verbose --set /etc/neutron/neutron.conf oslo_messaging_rabbit rabbit_ha_queues true
  register: cmd
  changed_when: "'changed' in cmd.stderr"

- name: openstack-command set notification_driver
  command: openstack-config --verbose --set /etc/neutron/neutron.conf DEFAULT notification_driver {{ neutron_notification_driver }}
  register: cmd
  changed_when: "'changed' in cmd.stderr"

- name: openstack-command set nova_url
  command: openstack-config --verbose --set /etc/neutron/neutron.conf DEFAULT nova_url http://{{ nova_private_vip | default('127.0.0.1') }}:{{ nova_osapi_compute_listen_port | default(8774) }}/v2
  register: cmd
  changed_when: "'changed' in cmd.stderr"

- name: openstack-command set notify_nova_on_port_status_changes
  command: openstack-config --verbose --set /etc/neutron/neutron.conf DEFAULT notify_nova_on_port_status_changes {{ neutron_notify_nova_on_port_status_changes }}
  register: cmd
  changed_when: "'changed' in cmd.stderr"

- name: openstack-command set notify_nova_on_port_data_changes
  command: openstack-config --verbose --set /etc/neutron/neutron.conf DEFAULT notify_nova_on_port_data_changes {{ neutron_notify_nova_on_port_data_changes }}
  register: cmd
  changed_when: "'changed' in cmd.stderr"

- name: openstack-command set auth_url
  command: openstack-config --verbose --set /etc/neutron/neutron.conf nova auth_url {{ keystone_auth_protocol | default('http') }}://{{ keystone_admin_vip }}:{{ keystone_auth_port | default(35357) }}/v2.0
  register: cmd
  changed_when: "'changed' in cmd.stderr"

- name: openstack-command set auth_plugin
  command: openstack-config --verbose --set /etc/neutron/neutron.conf nova auth_plugin password
  register: cmd
  changed_when: "'changed' in cmd.stderr"

- name: openstack-command set project_domain_id
  command: openstack-config --verbose --set /etc/neutron/neutron.conf nova project_domain_id default
  register: cmd
  changed_when: "'changed' in cmd.stderr"

- name: openstack-command set user_domain_id
  command: openstack-config --verbose --set /etc/neutron/neutron.conf nova user_domain_id default
  register: cmd
  changed_when: "'changed' in cmd.stderr"

- name: openstack-command set region_name
  command: openstack-config --verbose --set /etc/neutron/neutron.conf nova region_name {{ nova_region_name | default('regionOne') }}
  register: cmd
  changed_when: "'changed' in cmd.stderr"

- name: openstack-command set project_name
  command: openstack-config --verbose --set /etc/neutron/neutron.conf nova project_name services
  register: cmd
  changed_when: "'changed' in cmd.stderr"

- name: openstack-command set username
  command: openstack-config --verbose --set /etc/neutron/neutron.conf nova username compute
  register: cmd
  changed_when: "'changed' in cmd.stderr"

- name: openstack-command set password
  command: openstack-config --verbose --set /etc/neutron/neutron.conf nova password {{ nova_pass }}
  register: cmd
  changed_when: "'changed' in cmd.stderr"

- name: openstack-command set core_plugin
  command: openstack-config --verbose --set /etc/neutron/neutron.conf DEFAULT core_plugin {{ neutron_core_plugin }}
  register: cmd
  changed_when: "'changed' in cmd.stderr"

- name: openstack-command set service_plugins
  command: openstack-config --verbose --set /etc/neutron/neutron.conf DEFAULT service_plugins {{ neutron_service_plugins | join(',') }}
  register: cmd
  changed_when: "'changed' in cmd.stderr"

- name: openstack-command set router_scheduler_driver
  command: openstack-config --verbose --set /etc/neutron/neutron.conf DEFAULT router_scheduler_driver {{ neutron_router_scheduler_driver }}
  register: cmd
  changed_when: "'changed' in cmd.stderr"

- name: openstack-command set local,gre,flat,vxlan,vlan
  command: openstack-config --verbose --set /etc/neutron/plugins/ml2/ml2_conf.ini type_drivers {{ neutron_ml2_type_drivers }}
  register: cmd
  changed_when: "'changed' in cmd.stderr"

- name: openstack-command set tenant_network_types
  command: openstack-config --verbose --set /etc/neutron/plugins/ml2/ml2_conf.ini ml2 tenant_network_types {{ neutron_ml2_tenant_network_types }}
  register: cmd
  changed_when: "'changed' in cmd.stderr"

- name: openstack-command set mechanism_drivers
  command: openstack-config --verbose --set /etc/neutron/plugins/ml2/ml2_conf.ini ml2 mechanism_drivers openvswitch
  register: cmd
  changed_when: "'changed' in cmd.stderr"

- name: openstack-command set flat_networks
  command: openstack-config --verbose --set /etc/neutron/plugins/ml2/ml2_conf.ini ml2_type_flat flat_networks "*"
  register: cmd
  changed_when: "'changed' in cmd.stderr"

- name: openstack-command set tunnel_id_ranges
  command: openstack-config --verbose --set /etc/neutron/plugins/ml2/ml2_conf.ini ml2_type_gre tunnel_id_ranges {{ neutron_gre_tunnel_id_ranges }}
  register: cmd
  changed_when: "'changed' in cmd.stderr"

- name: openstack-command set vni_ranges
  command: openstack-config --verbose --set /etc/neutron/plugins/ml2/ml2_conf.ini ml2_type_vxlan vni_ranges {{ neutron_vxlan_vni_ranges }}
  register: cmd
  changed_when: "'changed' in cmd.stderr"

- name: openstack-command set vxlan_group
  command: openstack-config --verbose --set /etc/neutron/plugins/ml2/ml2_conf.ini ml2_type_vxlan vxlan_group {{ neutron_vxlan_group }}
  register: cmd
  changed_when: "'changed' in cmd.stderr"

- name: openstack-command set enable_security_group
  command: openstack-config --verbose --set /etc/neutron/plugins/ml2/ml2_conf.ini securitygroup enable_security_group {{ neutron_enable_security_group }}
  register: cmd
  changed_when: "'changed' in cmd.stderr"

- name: openstack-command set firewall_driver
  command: openstack-config --verbose --set /etc/neutron/plugins/ml2/ml2_conf.ini securitygroup firewall_driver True
  register: cmd
  changed_when: "'changed' in cmd.stderr"

- name: openstack-command set l3_ha
  command: openstack-config --verbose --set /etc/neutron/neutron.conf DEFAULT l3_ha True
  register: cmd
  changed_when: "'changed' in cmd.stderr"

- name: openstack-command set max_l3_agents_per_router
  command: openstack-config --verbose --set /etc/neutron/neutron.conf DEFAULT max_l3_agents_per_router 0
  register: cmd
  changed_when: "'changed' in cmd.stderr"

- name: openstack-command set min_l3_agents_per_router
  command: openstack-config --verbose --set /etc/neutron/neutron.conf DEFAULT min_l3_agents_per_router 2
  register: cmd
  changed_when: "'changed' in cmd.stderr"

- name: openstack-command set dhcp_agents_per_network
  command: openstack-config --verbose --set /etc/neutron/neutron.conf DEFAULT dhcp_agents_per_network {{ neutron_dhcp_agents_per_network }}
  register: cmd
  changed_when: "'changed' in cmd.stderr"

- name: create integration bridge
  openvswitch_bridge: bridge=br-int state=present
  when: use_neutron
  tags: neutron

- name: create tunneling bridge
  openvswitch_bridge: bridge=br-tun state=present
  when: neutron_ovs_tunnel_type is defined
  tags: neutron

- name: create external network bridge
  openvswitch_bridge: bridge={{ neutron_external_network_bridge | default('br-ex') }} state=present
  when: use_neutron_l3
  tags: neutron

- name: create ovs bridges
  openvswitch_bridge: bridge={{ item.bridge }} state=present
  with_items: neutron_ovs_bridges
  when: neutron_ovs_bridges is defined
  tags: neutron

- name: configure ovs ports
  openvswitch_port: bridge={{ item.bridge }} port={{ item.port }} state=present
  with_items: neutron_ovs_bridges
  when: neutron_ovs_bridges is defined
  tags: neutron

- name: stamp neutron database
  command: /usr/bin/neutron-db-manage --config-file /usr/share/neutron/neutron-dist.conf --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugin.ini stamp "{{ openstack_release }}"
  run_once: true
  tags: neutron

- name: disable neutron services
  service: name={{ item }} enabled=no 
  with_items:
    - neutron-server
    - neutron-dhcp-agent
    - neutron-metadata-agent
    - neutron-l3-agent
    - neutron-lbaas-agent
  when: use_neutron and use_ha_controller
  tags: neutron

- name: disable neutron-openvswitch-agent
  service: name=neutron-openvswitch-agent enabled=no 
  when: use_neutron_ovs and use_ha_controller
  tags: neutron

- include: cluster-constraints.yml
  tags: neutron
