---
- name: install iptables
  yum: name={{item}} state=present
  with_items:
    - iptables
    - iptables-services
    - iptables-utils
  tags: firewall

- name: flush current iptables
  command: iptables --flush
  tags: firewall

- name: apply iptables file
  template:
    src: "{{ item }}_iptables.j2"
    dest: /etc/sysconfig/iptables
    backup: yes
  when: inventory_hostname in groups[item]
  with_items:
    - "controller"
    - "compute"
    - "swift"
    - "scaleio"
  tags: firewall

- name: load new iptables
  service: name=iptables  state=restarted
  tags: firewall
