---
- name: register to RHN
  redhat_subscription:
    state: present
    username: "{{rhn_user}}"
    password: "{{rhn_pass}}"
    pool: "{{pool}}"

- name: enable repos
  command: subscription-manager repos
           --enable=rhel-7-server-rpms
           --enable=rhel-7-server-openstack-6.0-rpms
           --enable=rhel-server-rhscl-7-rpms
           --enable=rhel-ha-for-rhel-7-server-rpms
           --enable=rhel-7-server-optional-rpms