---
use_glance: true
default_store: file
glance_show_image_direct_url: false
glance_show_multiple_locations: false
glance_datadir: /var/lib/glance/images/
glance_api_port: 9292
glance_registry_port: 9191
