---

- name: update all packages
  yum:
   name: "*"
   state: latest
  when: not offline

- name: install base rpms
  yum: name={{ item }} state=present
  with_items:
    - libselinux-python
    - openssh-clients
    - ntp
    - bind-utils
    - openstack-utils
    - vim

