---
public_ipaddr: "{{ hostvars[inventory_hostname][ 'ansible_' + primary_if ].ipv4.address }}"
internal_ipaddr: "{{ hostvars[inventory_hostname][ 'ansible_' + private_if ].ipv4.address }}"
mongodb_bind_host: "{{ internal_ipaddr }}"
mongo_one: "{{hostvars[groups['controller'][0]]['ansible_hostname']}}"
#mongo_replSet: "{% for node in groups['controller'] %}{% if (hostvars[node]['ansible_hostname'] != mongo_one) and not loop.last %}[{{ hostvars[node]['ansible_hostname'] }}], {% elif hostvars[node]['ansible_hostname'] != mongo_one) %}]{% endif %} {% endfor %}"
