---
public_ipaddr: "{{ hostvars[inventory_hostname][ 'ansible_' + primary_if ].ipv4.address }}"
internal_ipaddr: "{{ hostvars[inventory_hostname][ 'ansible_' + private_if ].ipv4.address }}"
mysql_bind_address: "{{ internal_ipaddr }}"
wsrep_cluster_address: "{% for node in groups['controller'] %}{{ hostvars[node]['ansible_hostname'] }}{% if not loop.last %},{% endif %}{% endfor %} "
