---
- name: install common nova packages
  yum: pkg={{ item }} state=present
  with_items:
    - openstack-nova-common
    - python-nova
    - python-novaclient
  tags: nova

- name: Update api-paste.ini file
  command: openstack-config --verbose --set /etc/nova/api-paste.ini {{ item }}
  with_items:
    - "DEFAULT verbose true"
    - "filter:authtoken auth_host {{ keystone_admin_vip | default('127.0.0.1') }}"
    - "filter:authtoken admin_tenant_name services"
    - "filter:authtoken admin_user compute"
    - "filter:authtoken admin_password {{ nova_pass }}"
  register: cmd
  changed_when: "'unchanged' not in cmd.stderr"
  tags: nova
