---
- name: install & configure nova-common juno
  include: juno.yml
  when: openstack_release == 'juno'
  tags: nova

- name: install & configure nova-common kilo
  include: kilo.yml
  when: openstack_release == 'kilo'
  tags: nova
