---
- name: copy image to controller1
  copy: src={{image_location}}{{image_name}} dest=/root/{{image_name}}
  tags: demo
  run_once: true

- name: add image to glance
  command: >
    glance {{os_admin_auth}}
    --name {{image_short_name}}
    --file /root/{{image_name}}
    --disk-format {{image_disk_format}}
    --disk-container bare
    --is-public true
  run_once: true
  tags: demo

- name: copy cloud-init demo
  template: src=cloud_cfg_demo.txt.j2 dest=/root/cloud_cfg_demo.txt
  tags: demo

- name: launch an instance
  command: >
    nova {{os_demo_auth}}
    --flavor {{nova_boot_flavor}}
    name {{nova_boot_name}}
    --user-data /root/cloud_cfg_demo.txt
    --nic net-id={{internal_id.stdout}}
    --security-groups ssh-icmp
  run_once: true
  tags: demo
