---
# setups up test network for demo

- name: create demo project
  keystone_user:
    login_password: "{{admin_pass}}"
    endpoint: "{{keystone_adminurl}}"
    login_user: "{{admin_user}}"
    login_tenant_name: "{{admin_tenant}}"
    tenant: "{{demo_tenant}}"
    tenant_description: "demo tenant"
  run_once: true
  tags: demo

- name: add admin to demo tenant
  keystone_user:
    login_password: "{{admin_pass}}"
    endpoint: "{{keystone_adminurl}}"
    login_user: "{{admin_user}}"
    login_tenant_name: "{{admin_tenant}}"
    tenant: "{{demo_tenant}}"
    user: "{{demo_user}}"
    role: "_member_"
  run_once: true
  tags: demo

- name: create External Network.
  command: >
    neutron {{os_admin_auth}}
    net-create {{ext_net_name}}
  run_once: true
  tags: demo

- name: create external Subnet.
  command: >
    neutron
    {{os_admin_auth}}
    subnet-create {{ext_net_name}}
    --gateway {{ext_gateway}}
    --allocation-pool start={{ext_allocation.start}},end={{ext_allocation.end}}
    --disable-dhcp
    {{ext_network}}
  run_once: true
  tags: demo

- name: get external network ID
  shell: $(neutron net-list | grep {{ext_net_name}} | gawk -F' ' '{print $2}')"
  register: external_id
  run_once: true
  tags: demo

- name: create internal Network.
  command: >
    neutron
    {{os_demo_auth}}
    net-create {{int_net_name}}
  run_once: true
  tags: demo

- name: create internal Subnet.
  command: >
    neutron
    {{os_demo_auth}}
    subnet-create
    {{int_net_name}} {{int_network}}
  run_once: true
  tags: demo

- name: get external network ID
  shell: $(neutron net-list | grep {{int_net_name}} | gawk -F' ' '{print $2}')
  register: internal_id
  run_once: true
  tags: demo

- name: create router
  command: >
    neutron
    {{os_demo_auth}}
    router-create {{router_name}}
  run_once: true
  tags: demo

- name: set router-gateway
  command: neutron {{os_demo_auth}} router-gateway-set {{router_name}} {{external_id.stdout}}
  run_once: true
  tags: demo

- name: set internal router inteface in demo
  command: neutron {{os_demo_auth}} router-interface-add {{router_name}} {{internal_id.stdout}}
  run_once: true
  tags: demo
