---
# setups up test network for demo

- name: create demo project
  keystone_user:
    login_password: "{{admin_pass}}"
    endpoint: "{{keystone_adminurl}}"
    login_user: admin   
    login_tenant_name: admin
    tenant: demo
    tenant_description: "demo tenant"
  run_once: true
  tags: demo

- name: add admin to demo tenant
  keystone_user:
    login_password: "{{admin_pass}}"
    endpoint: "{{ keystone_adminurl }}"
    login_user: admin
    login_tenant_name: admin
    user: admin
    tenant: demo
    role: "_member_"
  run_once: true
  tags: demo

- name: create External Network.
  command: >
    neutron
    --os-auth-url "{{ keystone_adminurl}}"
    --os-tenant-name admin
    --os-username admin
    --os-password {{admin_pass}}
    net-create External
  run_once: true
  tags: demo

- name: create external Subnet.
  command: >
    neutron
    --os-auth-url "{{ keystone_adminurl}}"
    --os-tenant-name admin
    --os-username admin
    --os-password {{admin_pass}}
    subnet-create External 
    --name ext_sub
    --gateway 172.17.21.1
    --allocation-pool start=172.17.21.100,end=172.17.21.200
    --disable-dhcp 
    172.17.21.0/24
  run_once: true
  tags: demo

- name: create internal Network.
  command: >
    neutron
    --os-auth-url "{{ keystone_adminurl}}"
    --os-tenant-name demo
    --os-username admin
    --os-password {{admin_pass}}
    net-create internal_demo
  run_once: true
  tags: demo

- name: create internal Subnet.
  command: >
    neutron
    --os-auth-url "{{ keystone_adminurl}}"
    --os-tenant-name demo
    --os-username admin
    --os-password {{admin_pass}}
    subnet-create 
    --name int_sub
    internal_demo 192.168.100.0/24
  run_once: true
  tags: demo

- name: create router
  command: >
    neutron
    --os-auth-url "{{ keystone_adminurl}}"
    --os-tenant-name demo
    --os-username admin
    --os-password {{admin_pass}}
    router-create demo-router
  run_once: true
  tags: demo

- name: set router-gateway
  shell: "neutron --os-auth-url {{ keystone_adminurl}}  --os-tenant-name demo --os-username admin --os-password {{admin_pass}}  router-gateway-set $(router-list | grep demo-router| gwak -F' ' '{print $2}')  $(neutron net-list | grep External | gawk -F' ' '{print $2}')"
  run_once: true
  tags: demo 

- name: set internal router inteface in demo
  shell:  "neutron --os-auth-url {{ keystone_adminurl}} --os-tenant-name demo --os-username admin --os-password {{admin_pass}} router-interface-add demo router $(neutron net-list | grep demo_internal | gawk -F' ' '{print $2}') "
  run_once: true
  tags: demo    

