---
- name: create pacemaker resources for ceilometer control services
  pcs_resource: command=create name=ceilometer-{{ item }} type=lsb:openstack-ceilometer-{{ item }} clone=yes
  args:
    operations:
      - action: monitor
        options:
          start-delay: 10s
  run_once: true
  with_items:
    - central
    - collector
    - api
    - alarm-evaluator
    - alarm-notifier
    - notification
  tags: ceilometer
  
- name: create ceilometer-delay resource
  pcs_resource: command=create name=ceilometer-delay type=Delay clone=yes
  args:
    options:
      startdelay: 10
  run_once: true
  tags: ceilometer
